Conferences/SPLASH.md
_data/Committees.yaml

Please update the SPLASH steering committee as shown.

Update SPLASH Steering Committee.

---

Committees/SCChairs.md
Committees/X.html
_data/Committees.yaml

HI Matthew, 
I just updated the composition of the POPL Steering Committee
Cheers
Giuseppe Castagna

Changes in POPL Steering Committee composition

---

Conferences/POPL.md
_data/Committees.yaml

Yet another change in the Steering Committee for POPL. We are refining the rules, sorry.

POPL Steering Committee composition and rules

---

Conferences/ISMM.md

Adding ISMM 2018 information to the ISMM page.

Add ISMM 2018.

---

Resources/Climate.md

One more edit to the climate page, to link to a new report on carbon offsets.

Add a link to climate page

---

Resources/Climate.md

Some tidying on the Climate page, and a better pointer to one of the linked documents

Updates to Climate.md

---

Resources/EmpiricalEvaluation.md

Updates to the FAQ and the introductory text on the Empirical Eval page.

Empirical updates

---

Conferences/POPL.md

Updated various links on the page to point to the latest edition of POPL and to the latest version of the Principles of POPL
Thanks
Beppe

Updated link to latest version of Principles of POPL and to POPL 2019

---

_data/Committees.yaml

Updated POPL SC.

---

Committees/SCChairs.md
Conferences/SPLASH.md

This updates information on the SPLASH steering committee chair (me) and adds information about the latest conferences.

update SPLASH information

---

_data/Committees.yaml

The previous entry caused some recent confusion, so I hope this will help

clarified my listing as SPLASH SC chair

---

Membership.md
README.md
Resources/Author.md
Resources/Climate.md
Resources/Guidelines/ProChair.md
Resources/Guidelines/SCommittee.md

Just noticed that there are some HTML comments that are improperly formatted, so they are showing on the web-visible pages.

Quick / easy PR to fix comment visibility

---

Conferences/ISMM.md
Resources/Advice/VanLeunen-Lipton.md
_data/Committees.yaml

Two minor textual fixups.
I love this advice piece! In the details, it is hopelessly outdated ... but the high-level concepts are still relevant.

fixed up OCR? errors in 'How to have your abstract rejected'

---

Conferences/Onward.md

Added current conference and SC information, as well as most notable paper 2020

Updated for 2021

---

LongTermMentoring.md

Remove Adrian, and add the three new operations team members.

Update operations team

---

Conferences/MPLR.md

New (secure) links requested by MPLR Steering Committee chair

added new https links for MPLR content

---

_data/Achievement.yaml
_data/ICFP.yaml
_data/POPL.yaml
_data/Software.yaml

Updating awards:
* Software
* Achievement
* ICFP MIP'11
* POPL MIP'12

Updating awards

---

Conferences/ISMM.md

ISMM 2022 organization underway

added ISMM 2022 details and link

---

LongTermMentoring.md

Retire Ian, sub in Ronak

---

LongTermMentoring.md

SIGPLAN-M is in a transitional phase with leadership and the committee right now, so things are a bit in flux, but here is what we have so far

Latest committee members

---

Conferences/PLMW.md

Hi, I've updated the current PLMW SC and added links to 2022 instances.

members updated

---

Conferences/DLS.md

- add details on awards
- add past conferences

Updated DLS page

---

Highlights.md

Updated:
* Submission guidelines
* List of committee members

Updating the Research Highlights page

---

_data/AVCommittee.yaml

* Added two new AV Committee members from their participation in SPLASH'24.

AV Committee update

---

PACMPL/Editors.md

This information is used to get the PACMPL page https://dl.acm.org/journal/pacmpl/editorial-board
updated.

Update editor information to the current state of knowledge

---

LongTermMentoring.md

Adding myself, moving Nadia to Previous Chairs.

Update LongTermMentoring.md with new chair info

---

_data/HighlightsPapers.yaml

* Fixed a typo pointed by the authors of a highlight paper
* Slightly rephrased the citation

Fixed a typo in highlight citation

---

_data/AVCommittee.yaml

Added one new AV Committee member from their participation in POPL'25.
Move one member to Emeritus.
- Modified `_data/AVCommittee.yaml`

Update the AV Team

---

_data/Other.yaml

Proposed citation for 2024 SPLASH DS

2024 DS citation

---

Conferences/MPLR.md

Added the link to the latest conference.

Added MPLR’25

---

Conferences/PPOPP.md
_data/Committees.yaml

Added the recent three years of PPOPP info.
Updated the SC of PPOPP.

Updated the SC of PPOPP and added recent PPOPP conferences.
